// frontend/scripts/images/generate_app_icons.mjs
//
// Writes public/favicon.svg and rasterises the PWA / apple-touch icon set,
// all from src/brand/lexisMark.js — the one place the mark's geometry lives.
//
// Why this script exists. When the mark was redrawn on 4 Sep 2026 the four
// PNGs were stale by construction: nothing in the repo regenerated them, and
// the only reason they had matched the previous mark was that somebody
// exported them by hand on 29 Aug. Until the 23 Sep rebrand this script read
// favicon.svg and regex-scraped the waveform out of it; the favicon was
// itself a hand-kept copy of LexisMark.jsx. Now the favicon is an OUTPUT, so
// there is no hand-kept copy left to drift.
//
// Rendered through playwright-core + the preinstalled Chromium rather than
// sharp: sharp is NOT in this project's node_modules, while playwright-core
// is, and Chromium lives at /opt/pw-browsers in the container. Never run
// `playwright install`.
//
// Which variant goes where:
//   favicon.svg, icon-192/512   rounded tile: shown as-is by browsers and
//                               launchers that do not mask
//   icon-512-maskable           full-bleed square, glyph shrunk to 0.8 —
//                               Android crops a maskable icon to its own
//                               shape inside an ~80% safe zone; a rounded
//                               tile there gets its corners rounded twice
//   apple-touch-icon            full-bleed square at full size — iOS applies
//                               its own squircle and has no safe-zone rule,
//                               and a transparent rounded corner would show
//                               up black behind Apple's mask
//
// Run with: node scripts/images/generate_app_icons.mjs
import { chromium } from 'playwright-core';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { markSvg } from '../../src/brand/lexisMark.js';

const here = dirname(fileURLToPath(import.meta.url));
const publicDir = join(here, '..', '..', 'public');

const favicon = markSvg({ variant: 'tile', label: 'LEXIS' });
writeFileSync(
  join(publicDir, 'favicon.svg'),
  `<!-- GENERATED by scripts/images/generate_app_icons.mjs from src/brand/lexisMark.js. Do not edit by hand. -->\n${favicon}\n`
);
console.log('wrote favicon.svg');

const targets = [
  { file: 'icon-512.png', size: 512, source: favicon },
  { file: 'icon-192.png', size: 192, source: favicon },
  { file: 'apple-touch-icon.png', size: 180, source: markSvg({ variant: 'square' }) },
  { file: 'icon-512-maskable.png', size: 512, source: markSvg({ variant: 'square', scale: 0.8 }) }
];

const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
try {
  for (const { file, size, source } of targets) {
    const page = await browser.newPage({
      viewport: { width: size, height: size },
      deviceScaleFactor: 1
    });
    await page.setContent(
      `<style>html,body{margin:0;padding:0;background:transparent}
       svg{display:block;width:${size}px;height:${size}px}</style>${source}`
    );
    const buf = await page.screenshot({ omitBackground: true });
    writeFileSync(join(publicDir, file), buf);
    await page.close();
    console.log(`wrote ${file} (${size}x${size}, ${buf.length} bytes)`);
  }
} finally {
  await browser.close();
}
