import React, { useMemo, useState } from 'react';
import { Mic, ShieldCheck, Zap, Globe, Check, ArrowRight, MessageCircle, Repeat, TrendingUp } from 'lucide-react';
import LexisMark from '../components/LexisMark';
import { buildFaqJsonLd, SITE_URL } from '../data/structuredData';
import { useSeo } from '../lib/useSeo';
import { FAQS, LANDING_DESCRIPTION_EN, LANDING_DESCRIPTION_TH, PRICING_TEASER_EN, PRICING_TEASER_TH } from '../content/facts';

// Same key LexisApp.jsx reads on session start ('en' = practicing English,
// 'th' = practicing Thai). Setting it here before navigating to /app means
// the direction picked on the landing page is what the first session
// actually uses, without needing a query param or extra plumbing.
const TARGET_LANGUAGE_STORAGE_KEY = 'lexis_target_language';

// Generated the same way as the in-app avatar photos (see
// scripts/avatar/lexis-tutor-photo-notes.md, "Marketing hero photo") —
// same identity, full body, warm welcoming pose. This is what the hero
// redesign is actually about: a real depiction of LEXIS instead of copy
// floating in empty space.
const HERO_PHOTO_URL = '/marketing/lexis-tutor-hero.jpg';

// Responsive variants (AVIF/WebP/JPEG at 480/800/1200px) generated by
// frontend/scripts/images/generate_hero_srcset.mjs — Stage 5 of the
// remediation brief. The original 1200x1607 JPEG (~161KB) shipped as a
// single fixed-size file with fetchpriority="high", the largest paint
// on a mobile-first Thai audience, at a resolution far bigger than the
// photo's actual rendered CSS size (this container tops out at
// md:max-w-sm = 384px — see the <picture>'s sizes attribute below,
// which mirrors that same breakpoint set exactly rather than guessing).
const HERO_SRCSET = (ext) => [480, 800, 1200].map((w) => `/marketing/lexis-tutor-hero-${w}.${ext} ${w}w`).join(', ');
const HERO_SIZES = '(min-width: 768px) 384px, (min-width: 640px) 320px, 256px';

// Keyed by display language (Stage 4: /th is a real page now, not just a
// client-side toggle) rather than one hardcoded English array.
const HOW_IT_WORKS = {
  en: [
    { icon: Mic, title: 'Start talking', desc: 'Tap one button and start speaking: no typing, no scripts to read from.' },
    { icon: MessageCircle, title: 'LEXIS responds live', desc: "It listens, replies, and corrects you gently mid-conversation, the way a patient tutor would." },
    { icon: TrendingUp, title: 'See what to work on', desc: 'After each session, get a plain-language summary of what you did well and what to practice next.' }
  ],
  th: [
    { icon: Mic, title: 'เริ่มพูด', desc: 'แตะปุ่มเดียวแล้วเริ่มพูดได้เลย ไม่ต้องพิมพ์ ไม่ต้องท่องสคริปต์' },
    { icon: MessageCircle, title: 'LEXIS ตอบกลับสด ๆ', desc: 'ฟัง ตอบกลับ และช่วยแก้ไขให้อย่างอ่อนโยนระหว่างสนทนา เหมือนติวเตอร์ใจเย็น' },
    { icon: TrendingUp, title: 'ดูว่าควรฝึกอะไรต่อ', desc: 'หลังจบแต่ละเซสชัน จะได้สรุปผลแบบเข้าใจง่ายว่าทำได้ดีตรงไหน และควรฝึกอะไรต่อ' }
  ]
};

// Sitewide chrome strings (header, badge, section headings, trust strip,
// footer) that aren't part of the direction/display content matrix above
// — these don't depend on which language a visitor is learning, only on
// which language the page itself is displayed in.
const CHROME = {
  en: {
    pricing: 'Pricing',
    getStarted: 'Get Started',
    heroBadge: 'Talk in real time: no awkward pauses, no typing',
    howItWorks: 'How it works',
    trust: [
      'Gentle, real-time grammar correction',
      'Jump in and interrupt LEXIS anytime',
      'Review what you practiced, anytime (paid plans)',
      'No waiting, no scheduling: practice the moment you want to'
    ],
    faqHeading: 'Frequently asked questions',
    learnEnglish: 'Learn English',
    learnThai: 'Learn Thai',
    liveVoice: 'Live voice, ready when you are',
    heroAlt: 'LEXIS, your voice conversation partner, ready to start a practice session',
    footerTrust: 'Private & secure • Payments handled by Stripe',
    privacy: 'Privacy',
    terms: 'Terms',
    refunds: 'Refunds',
    community: 'Community'
  },
  th: {
    pricing: 'ราคา',
    getStarted: 'เริ่มเลย',
    heroBadge: 'พูดคุยแบบเรียลไทม์ ไม่ต้องพิมพ์ ไม่ต้องรอ',
    howItWorks: 'วิธีใช้งาน',
    trust: [
      'แก้ไขไวยากรณ์แบบเรียลไทม์อย่างอ่อนโยน',
      'พูดแทรก LEXIS ได้ทุกเมื่อ',
      'ทบทวนสิ่งที่ฝึกได้ทุกเมื่อ (แพ็กเกจแบบเสียเงิน)',
      'ไม่ต้องรอ ไม่ต้องนัดเวลา ฝึกได้ทันทีที่อยากฝึก'
    ],
    faqHeading: 'คำถามที่พบบ่อย',
    learnEnglish: 'เรียนภาษาอังกฤษ',
    learnThai: 'เรียนภาษาไทย',
    liveVoice: 'พูดคุยสด พร้อมเมื่อคุณพร้อม',
    heroAlt: 'LEXIS คู่สนทนาฝึกพูดของคุณ พร้อมเริ่มฝึกได้ทุกเมื่อ',
    footerTrust: 'ปลอดภัยและเป็นส่วนตัว • ชำระเงินผ่าน Stripe',
    privacy: 'นโยบายความเป็นส่วนตัว',
    terms: 'ข้อกำหนดการใช้งาน',
    refunds: 'การคืนเงิน',
    community: 'Community'
  }
};

export default function LandingPage({ navigateTo, lang = 'en' }) {
  // Display language is now which route you're on ('/' = en, '/th' = th —
  // Stage 4), not local component state — a crawler or a visitor who
  // shares a link needs a real, indexable URL per language, not a client-
  // side toggle invisible to anything that doesn't run JS. The toggle
  // button below now navigates instead of calling a setter.
  const c = CHROME[lang];
  const [direction, setDirection] = useState(() => {
    try {
      return localStorage.getItem(TARGET_LANGUAGE_STORAGE_KEY) === 'th' ? 'th' : 'en';
    } catch {
      return 'en'; // localStorage can throw in some privacy modes — default, don't crash the page.
    }
  });

  const selectDirection = (dir) => {
    setDirection(dir);
    try {
      localStorage.setItem(TARGET_LANGUAGE_STORAGE_KEY, dir);
    } catch {
      // Privacy-mode localStorage throw — the choice just won't persist across visits.
    }
  };

  const goPractice = () => {
    // Direction is already persisted by selectDirection; this just launches
    // the app with whichever direction is currently selected.
    navigateTo('/app');
  };

  // content[direction][displayLang] — direction is which language the student
  // is learning (en = English, th = Thai), displayLang is which language
  // this page's own copy is shown in. Independent axes: an English speaker
  // learning Thai and a Thai speaker learning English both toggle `lang` to
  // read the page comfortably regardless of which direction they picked.
  const content = {
    en: {
      en: {
        heroTitle: 'Practice Speaking English Out Loud with LEXIS',
        heroSub: 'A friendly conversation partner who listens, replies, and gently corrects you in real time. Built for students, professionals, and anyone prepping for interviews, travel, or work. Practice as much as you want, whenever you want.',
        cta: 'Try It Free',
        pricingTeaser: PRICING_TEASER_EN,
        viewPricing: 'View full pricing'
      },
      th: {
        heroTitle: 'ฝึกพูดภาษาอังกฤษออกเสียงจริงกับ LEXIS',
        heroSub: 'LEXIS ฟัง พูดคุย และช่วยแก้ไขให้คุณแบบเรียลไทม์ เหมาะกับนักเรียน คนทำงาน และใครก็ตามที่กำลังเตรียมสัมภาษณ์งาน เดินทาง หรือทำงาน ฝึกได้เท่าที่อยากฝึก เมื่อไหร่ก็ได้',
        cta: 'ลองใช้ฟรี',
        pricingTeaser: PRICING_TEASER_TH,
        viewPricing: 'ดูแพ็กเกจทั้งหมด'
      }
    },
    th: {
      en: {
        heroTitle: 'Practice Speaking Thai Out Loud with LEXIS',
        heroSub: 'A friendly conversation partner who listens, replies, and gently corrects you in real time. Built for students, professionals, and anyone prepping for interviews, travel, or work. Practice as much as you want, whenever you want.',
        cta: 'Try It Free',
        pricingTeaser: PRICING_TEASER_EN,
        viewPricing: 'View full pricing'
      },
      th: {
        heroTitle: 'ฝึกพูดภาษาไทยออกเสียงจริงกับ LEXIS',
        heroSub: 'LEXIS ฟัง พูดคุย และช่วยแก้ไขให้คุณแบบเรียลไทม์ เหมาะกับนักเรียน คนทำงาน และใครก็ตามที่กำลังเตรียมสัมภาษณ์งาน เดินทาง หรือทำงาน ฝึกได้เท่าที่อยากฝึก เมื่อไหร่ก็ได้',
        cta: 'ลองใช้ฟรี',
        pricingTeaser: PRICING_TEASER_TH,
        viewPricing: 'ดูแพ็กเกจทั้งหมด'
      }
    }
  };

  const t = content[direction][lang];
  const enUrl = `${SITE_URL}/`;
  const thUrl = `${SITE_URL}/th`;

  // FAQ JSON-LD now mirrors whichever language's FAQ text is actually
  // visible below (FAQS.en or FAQS.th, both real content since Stage 4) —
  // no longer gated to English only.
  const faqJsonLd = useMemo(() => buildFaqJsonLd(lang), [lang]);

  useSeo({
    title: lang === 'th' ? 'LEXIS | ฝึกพูดภาษาอังกฤษและภาษาไทยออกเสียงจริง' : 'LEXIS | Practice Speaking English & Thai Out Loud',
    description: lang === 'th' ? LANDING_DESCRIPTION_TH : LANDING_DESCRIPTION_EN,
    canonical: lang === 'th' ? thUrl : enUrl,
    htmlLang: lang,
    // Reciprocal per Google's hreflang requirement — each language version
    // lists every version including itself. x-default points at the
    // English page (the site's language-neutral fallback).
    hreflang: [
      { hrefLang: 'en', href: enUrl },
      { hrefLang: 'th', href: thUrl },
      { hrefLang: 'x-default', href: enUrl }
    ],
    jsonLd: { 'jsonld-faq': faqJsonLd }
  });

  return (
    <div className="min-h-screen lexis-canvas-gradient text-lexis-ink font-sans">
      {/* Header */}
      <header className="w-full max-w-6xl mx-auto p-4 sm:p-6 flex items-center justify-between border-b border-lexis-ink/10 gap-2">
        <div className="flex items-center space-x-2 sm:space-x-3 min-w-0">
          <div className="p-2 bg-teal-600/10 border border-teal-600/20 rounded-xl text-teal-700 flex-shrink-0">
            <LexisMark className="w-6 h-6" />
          </div>
          <span className="text-lg sm:text-xl font-display font-semibold text-lexis-ink whitespace-nowrap">
            LEXIS
          </span>
        </div>

        {/* Four interactive elements (language, pricing, CTA) genuinely
            don't fit a 375px-wide header with full labels on everything —
            an earlier pass just hid Pricing below `sm`, which a re-audit
            correctly called out (a mobile visitor literally cannot find
            pricing). The fix here is to actually make everything fit —
            icon-only language toggle and a tighter CTA on small screens —
            rather than hide the thing that didn't fit. */}
        <div className="flex items-center gap-1.5 sm:gap-4 flex-shrink-0">
          <button
            onClick={() => navigateTo(lang === 'en' ? '/th' : '/')}
            aria-label={lang === 'en' ? 'Switch page language to Thai' : 'Switch page language to English'}
            className="flex items-center justify-center sm:justify-start gap-2 bg-white border border-lexis-ink/10 rounded-xl text-xs text-lexis-ink/70 hover:border-teal-600/40 transition-all min-h-[44px] min-w-[44px] px-2.5 sm:px-3"
          >
            <Globe className="w-4 h-4 text-teal-700 flex-shrink-0" />
            <span className="hidden sm:inline">{lang === 'en' ? 'ไทย' : 'English'}</span>
          </button>
          <button
            onClick={() => navigateTo(lang === 'th' ? '/th/pricing' : '/pricing')}
            className="text-xs sm:text-sm text-lexis-ink/70 hover:text-lexis-ink transition-colors min-h-[44px] px-1"
          >
            {c.pricing}
          </button>
          <button
            onClick={goPractice}
            className="px-3 sm:px-5 py-2.5 bg-lexis-action hover:bg-lexis-action-dark text-white font-semibold text-xs sm:text-sm rounded-xl transition-all shadow-lg shadow-lexis-action/20 flex items-center gap-1.5 sm:gap-2 min-h-[44px] whitespace-nowrap"
          >
            <span>{c.getStarted}</span>
            <ArrowRight className="w-4 h-4 flex-shrink-0" />
          </button>
        </div>
      </header>

      {/* Hero — split layout: copy on the left, an actual photo of LEXIS on
          the right. The previous version was copy floating alone on a flat
          background, which read as generic/faceless. A real depiction of
          who a student is talking to does more for "impressive" than any
          amount of copy polish alone would. */}
      <section className="w-full max-w-6xl mx-auto px-6 py-16 md:py-20 grid md:grid-cols-2 gap-12 items-center">
        <div className="text-center md:text-left">
          <div className="inline-flex items-center space-x-2 px-3 py-1 bg-teal-600/10 border border-teal-600/20 rounded-full text-xs text-teal-700 mb-6">
            <Zap className="w-3.5 h-3.5" />
            <span>{c.heroBadge}</span>
          </div>
          <h1 className="font-display font-semibold text-4xl md:text-5xl tracking-tight mb-6 text-lexis-ink leading-tight text-balance">
            {t.heroTitle}
          </h1>
          <p className="text-lg md:text-xl text-lexis-ink/60 mb-6 max-w-xl mx-auto md:mx-0 leading-relaxed">
            {t.heroSub}
          </p>

          {/* Which language to practice — sets the tutor persona used the
              next time a session starts. Two-way by design: English speakers
              learning Thai and Thai speakers learning English both land here. */}
          <div className="inline-flex items-center bg-white border border-lexis-ink/10 rounded-full p-1 mb-6 text-sm shadow-sm">
            <button
              onClick={() => selectDirection('en')}
              aria-pressed={direction === 'en'}
              className={`px-4 py-2 rounded-full font-semibold transition-colors min-h-[44px] ${direction === 'en' ? 'bg-teal-600 text-white' : 'text-lexis-ink/50 hover:text-lexis-ink'}`}
            >
              {c.learnEnglish}
            </button>
            <button
              onClick={() => selectDirection('th')}
              aria-pressed={direction === 'th'}
              className={`px-4 py-2 rounded-full font-semibold transition-colors min-h-[44px] ${direction === 'th' ? 'bg-teal-600 text-white' : 'text-lexis-ink/50 hover:text-lexis-ink'}`}
            >
              {c.learnThai}
            </button>
          </div>

          <div>
            <button
              onClick={goPractice}
              className="px-8 py-4 bg-lexis-action hover:bg-lexis-action-dark hover:scale-105 transition-transform text-white font-display font-semibold text-lg rounded-2xl shadow-xl shadow-lexis-action/25 flex items-center space-x-3 mx-auto md:mx-0"
            >
              <Mic className="w-5 h-5" />
              <span>{t.cta}</span>
            </button>
          </div>
          <div className="mt-6 flex items-center justify-center md:justify-start space-x-3 text-sm">
            <span className="text-lexis-ink/50">{t.pricingTeaser}</span>
            <button onClick={() => navigateTo('/pricing')} className="text-teal-700 hover:text-teal-800 font-medium underline underline-offset-2">
              {t.viewPricing}
            </button>
          </div>
        </div>

        {/* LEXIS herself — a soft teal glow behind the photo ties it to the
            live-session avatar treatment elsewhere in the app, without
            reusing lexis-navy as a background here (this page stays on the
            warm canvas per the visual-system doc's "marketing pages kept
            their existing IA" note).

            The photo is a generated image (see
            scripts/avatar/lexis-tutor-photo-notes.md). A previous pass here
            added an explicit "AI-generated" disclosure caption for trust
            reasons; reversed 20 Aug 2026 on direct product-positioning
            instruction — the caption and any other "AI" wording in this
            page's own copy were removed. The underlying image and its
            generation process didn't change, only whether the marketing
            copy calls attention to it. */}
        <div className="relative flex justify-center md:justify-end">
          <div className="absolute w-72 h-72 md:w-96 md:h-96 bg-teal-500/20 rounded-full blur-3xl pointer-events-none" />
          <div className="relative w-64 sm:w-80 md:w-full md:max-w-sm aspect-[3/4] rounded-[2rem] overflow-hidden border border-white shadow-2xl shadow-teal-900/10">
            <picture>
              <source type="image/avif" srcSet={HERO_SRCSET('avif')} sizes={HERO_SIZES} />
              <source type="image/webp" srcSet={HERO_SRCSET('webp')} sizes={HERO_SIZES} />
              <img
                src={HERO_PHOTO_URL}
                srcSet={HERO_SRCSET('jpg')}
                sizes={HERO_SIZES}
                alt={c.heroAlt}
                className="w-full h-full object-cover"
                width="1200"
                height="1607"
                loading="eager"
                fetchpriority="high"
              />
            </picture>
          </div>
          <div className="absolute -bottom-4 left-1/2 -translate-x-1/2 md:left-auto md:right-6 md:translate-x-0 bg-white border border-lexis-ink/10 rounded-2xl shadow-lg px-4 py-2.5 flex items-center gap-2 text-xs font-medium text-lexis-ink whitespace-nowrap">
            <span className="w-2 h-2 rounded-full bg-teal-500 animate-pulse" />
            <span>{c.liveVoice}</span>
          </div>
        </div>
      </section>

      {/* How it works — three concrete steps instead of adjective-heavy
          copy. Short, literal sentences here also read cleanly to search
          crawlers and answer engines, not just human visitors. */}
      <section className="w-full max-w-5xl mx-auto px-6 py-10">
        <h2 className="font-display font-semibold text-2xl text-center mb-10">{c.howItWorks}</h2>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
          {HOW_IT_WORKS[lang].map(({ icon: Icon, title, desc }, i) => (
            <div key={title} className="bg-white border border-lexis-ink/10 rounded-2xl p-6">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-8 h-8 flex items-center justify-center rounded-full bg-lexis-action/10 text-lexis-action-dark font-display font-semibold text-sm flex-shrink-0">
                  {i + 1}
                </div>
                <Icon className="w-5 h-5 text-teal-700" />
              </div>
              <div className="font-semibold text-sm mb-1.5">{title}</div>
              <div className="text-sm text-lexis-ink/60 leading-relaxed">{desc}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Trust strip — four short bullets, not three. The fourth
          ("No waiting, no scheduling...") is where "How is this different
          from a language exchange app?" moved to when the FAQ list below
          got trimmed (19 Aug 2026) — a punchy differentiator fits a bullet
          better than a whole FAQ block, and this is the section that
          already exists for exactly this kind of claim. */}
      <section className="w-full max-w-5xl mx-auto px-6 py-10">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 text-xs text-lexis-ink/60">
          <div className="flex items-center space-x-2 bg-white border border-lexis-ink/10 rounded-xl px-4 py-3">
            <Check className="w-4 h-4 text-teal-600 flex-shrink-0" />
            <span>{c.trust[0]}</span>
          </div>
          <div className="flex items-center space-x-2 bg-white border border-lexis-ink/10 rounded-xl px-4 py-3">
            <Repeat className="w-4 h-4 text-teal-600 flex-shrink-0" />
            <span>{c.trust[1]}</span>
          </div>
          <div className="flex items-center space-x-2 bg-white border border-lexis-ink/10 rounded-xl px-4 py-3">
            <Check className="w-4 h-4 text-teal-600 flex-shrink-0" />
            <span>{c.trust[2]}</span>
          </div>
          <div className="flex items-center space-x-2 bg-white border border-lexis-ink/10 rounded-xl px-4 py-3">
            <Zap className="w-4 h-4 text-teal-600 flex-shrink-0" />
            <span>{c.trust[3]}</span>
          </div>
        </div>
      </section>

      {/* FAQ — plain question/answer pairs, marked up with <details>/<summary>
          (real semantic HTML, not just styled divs) and mirrored as
          FAQPage JSON-LD in index.html. This is squarely aimed at answer
          engines (ChatGPT search, Perplexity, Google's AI overviews) as
          much as human visitors — clear, self-contained Q&A is exactly
          the shape those tools quote from. */}
      <section className="w-full max-w-3xl mx-auto px-6 py-14">
        <h2 className="font-display font-semibold text-2xl text-center mb-8">{c.faqHeading}</h2>
        <div className="space-y-3">
          {FAQS[lang].map(({ q, a }) => (
            <details key={q} className="group bg-white border border-lexis-ink/10 rounded-2xl p-4 open:shadow-sm">
              <summary className="cursor-pointer list-none flex items-center justify-between gap-3 font-semibold text-sm text-lexis-ink">
                <span>{q}</span>
                <ArrowRight className="w-4 h-4 text-lexis-ink/30 flex-shrink-0 transition-transform group-open:rotate-90" />
              </summary>
              <p className="mt-3 text-sm text-lexis-ink/60 leading-relaxed">{a}</p>
            </details>
          ))}
        </div>
      </section>

      {/* Footer — the "Private & secure" claim used to have nothing
          behind it (flagged in a re-audit: U6). Now links to the actual
          Privacy Policy that explains what that claim means. */}
      <footer className="w-full max-w-6xl mx-auto p-6 border-t border-lexis-ink/10 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-lexis-ink/40">
        <div className="flex items-center space-x-2">
          <ShieldCheck className="w-4 h-4 text-teal-600" />
          <span>{c.footerTrust}</span>
        </div>
        <div className="flex items-center gap-4">
          {/* Terms/Privacy/Refund/Community only exist in English so far
              (Stage 4 scoped /th to the landing + pricing pages) — link
              labels follow the page's display language, the destination
              doesn't. */}
          <button onClick={() => navigateTo('/community')} className="hover:text-lexis-ink transition-colors">{c.community}</button>
          <button onClick={() => navigateTo('/privacy')} className="hover:text-lexis-ink transition-colors">{c.privacy}</button>
          <button onClick={() => navigateTo('/terms')} className="hover:text-lexis-ink transition-colors">{c.terms}</button>
          <button onClick={() => navigateTo('/refund')} className="hover:text-lexis-ink transition-colors">{c.refunds}</button>
          <span>© 2026 LEXIS</span>
        </div>
      </footer>
    </div>
  );
}
