// frontend/src/pages/TermsPage.jsx
//
// Scaffolded per the remediation brief's U6 finding (no terms page
// existed at all). Same rule as PrivacyPage.jsx: real product facts are
// stated plainly; anything requiring an actual business/legal decision
// is a loud <Todo> marker, not a guess.
import React from 'react';
import LegalPageShell, { Todo } from '../components/LegalPageShell';
import { useSeo } from '../lib/useSeo';
import { SITE_URL } from '../data/structuredData';
import { PRICING, TRIAL, VAT } from '../content/facts';

export default function TermsPage({ navigateTo }) {
  useSeo({
    title: 'Terms of Service | LEXIS',
    description: 'The terms for using LEXIS and subscribing to a paid plan.',
    canonical: `${SITE_URL}/terms`
  });

  return (
    <LegalPageShell navigateTo={navigateTo} title="Terms of Service" lastUpdated="17 August 2026">
      <p>
        Sections marked <Todo>—</Todo> below need a real decision from
        LEXIS before this page is a complete, enforceable terms document
        — treat it as a scaffold, not finished legal copy.
      </p>

      <h2 className="font-display font-semibold text-lg text-lexis-ink pt-2">What LEXIS is</h2>
      <p>
        LEXIS is a voice conversation practice tool for spoken English
        and Thai, delivered through a web browser. A free trial gives
        every new account {TRIAL.minutes} minutes of practice
        {TRIAL.cardRequired ? '' : ', no card required'}. Paid plans are
        ฿{PRICING.weekly.thb}/week or ฿{PRICING.monthly.thb}/month for
        unlimited practice, billed on a recurring basis through Stripe
        until cancelled. {VAT.registered ? '' : 'No VAT applies — LEXIS is not a VAT-registered business.'}
      </p>

      <h2 className="font-display font-semibold text-lg text-lexis-ink pt-2">Your account</h2>
      <p>
        You're responsible for keeping your login credentials to
        yourself and for activity on your account. LEXIS reserves the
        right to suspend an account for abuse of the service —
        <Todo>define "abuse" concretely (e.g. sharing one paid account
        across many people, attempting to extract the underlying AI
        model's system prompt, automated/bot usage) rather than leaving
        it undefined.</Todo>
      </p>

      <h2 className="font-display font-semibold text-lg text-lexis-ink pt-2">Cancelling</h2>
      <p>
        You can cancel a paid plan at any time; see the
        {' '}<button onClick={() => navigateTo('/refund')} className="text-teal-700 hover:text-teal-800 underline underline-offset-2">Refund &amp; Cancellation Policy</button>{' '}
        for exactly what that means for a plan already in progress.
      </p>

      <h2 className="font-display font-semibold text-lg text-lexis-ink pt-2">What LEXIS is not</h2>
      <p>
        LEXIS is a practice tool, not a certified language qualification,
        a substitute for professional language instruction, or a
        guarantee of any specific learning outcome. Feedback and
        corrections are generated by an AI model and may occasionally be
        wrong.
      </p>

      <h2 className="font-display font-semibold text-lg text-lexis-ink pt-2">Changes to these terms</h2>
      <p>
        <Todo>Define the actual process for notifying users of material
        changes (e.g. email, in-app notice) rather than a generic "we
        may update this page" statement with no real mechanism behind
        it.</Todo>
      </p>

      <h2 className="font-display font-semibold text-lg text-lexis-ink pt-2">Governing law</h2>
      <p>
        <Todo>State the governing law / jurisdiction and the legal
        entity these terms are with — see PrivacyPage.jsx's equivalent
        section, same underlying gap.</Todo>
      </p>
    </LegalPageShell>
  );
}
